# Generated by Django 4.2.11 on 2024-03-14 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vehicle_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='colour',
            new_name='color',
        ),
    ]
